CREATE TABLE checkins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  habit_id BIGINT NOT NULL,
  checkin_date DATE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_checkins_habit
    FOREIGN KEY (habit_id) REFERENCES habits(id),

  CONSTRAINT uq_checkins_habit_date
    UNIQUE (habit_id, checkin_date)
);
